name: Trigger auto deployment for bit-task-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bit-task-api-AutoDeployTrigger-f4fadac5-5be2-4a9c-9b55-0c6b3df146ea.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BITTASKAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BITTASKAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BITTASKAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: apiimage.azurecr.io
          registryUsername: ${{ secrets.BITTASKAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BITTASKAPI_REGISTRY_PASSWORD }}
          containerAppName: bit-task-api
          resourceGroup: bit-task
          imageToBuild: apiimage.azurecr.io/bit-task-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


